In [12]:
import numpy as np
array1 = np.array(range(30))
array2 = np.array([2,3,5])

with open('Homework_array.npz', 'wb') as f:
    np.savez(f, first_array=array1, second_array=array2)

In [13]:
import numpy as np
Homeworkfile = np.load('Homework_array.npz')
npzfile = np.load('multi_array.npz')
npyfile = np.load('one_array.npy')
x = np.load('one_array.npy')

print(Homeworkfile['first_array'])
print(Homeworkfile['second_array'])
print(npzfile['array1'])
print(npzfile['array1'])
print(npzfile['array3'])
print(x)

a1 = Homeworkfile['first_array']
a2 = Homeworkfile['second_array']
b1 = npzfile['array1']
b2 = npzfile['array2']
b3 = npzfile['array3']
c1 = x

with open('Homework_multi_array.npz', 'wb') as f:
    np.savez(f,array1= a1,
                array2= a2,
                array3= b1,
                array4= b2,
                array5= b3,
                array6= c1)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0.5788873  0.69082947 0.04922545 0.86517602 0.29889969 0.55285575
 0.69389689 0.49183867 0.8308363  0.06454569]
[1 2]


In [15]:
import numpy as np
npzfile = np.load('Homework_multi_array.npz')
print(npzfile['array1'])
print(npzfile['array2'])
print(npzfile['array3'])
print(npzfile['array4'])
print(npzfile['array5'])
print(npzfile['array6'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[0 1 2 3 4 5 6 7 8 9]
[1 2 3]
[0.5788873  0.69082947 0.04922545 0.86517602 0.29889969 0.55285575
 0.69389689 0.49183867 0.8308363  0.06454569]
[1 2]
